"""add analytics columns

Revision ID: 0c2e8e704cd4
Revises: a533beaed1f1
Create Date: 2026-04-02 09:40:59.555862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c2e8e704cd4'
down_revision: Union[str, Sequence[str], None] = 'a533beaed1f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_reports', sa.Column('total_words', sa.Integer(), nullable=False))
    op.add_column('session_reports', sa.Column('assertiveness_score', sa.Integer(), nullable=False))
    op.drop_column('users', 'target_language')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('target_language', sa.VARCHAR(), server_default=sa.text("'English'::character varying"), autoincrement=False, nullable=True))
    op.drop_column('session_reports', 'assertiveness_score')
    op.drop_column('session_reports', 'total_words')
    # ### end Alembic commands ###
