"""full_schema_v2

Revision ID: a533beaed1f1
Revises: 
Create Date: 2026-03-29 12:25:07.678572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a533beaed1f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('age_group', sa.String(), nullable=True),
    sa.Column('profession', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anonymous_sessions_token'), 'anonymous_sessions', ['token'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avatar_initials', sa.String(length=4), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('streak_freeze_count', sa.Integer(), nullable=False),
    sa.Column('streak_frozen_today', sa.Boolean(), nullable=False),
    sa.Column('daily_goal_minutes', sa.Integer(), nullable=False),
    sa.Column('weekly_session_target', sa.Integer(), nullable=False),
    sa.Column('language_level', sa.String(), nullable=False),
    sa.Column('profession', sa.String(), nullable=True),
    sa.Column('notification_prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skill_fluency', sa.Float(), nullable=False),
    sa.Column('skill_grammar', sa.Float(), nullable=False),
    sa.Column('skill_pronunciation', sa.Float(), nullable=False),
    sa.Column('skill_vocabulary', sa.Float(), nullable=False),
    sa.Column('skill_confidence', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('earned_at', sa.String(), server_default=sa.text('CAST(now() AS VARCHAR)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_user_id'), 'achievements', ['user_id'], unique=False)
    op.create_table('anxiety_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('CAST(now() AS VARCHAR)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anxiety_assessments_user_id'), 'anxiety_assessments', ['user_id'], unique=False)
    op.create_table('communication_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('overall_filler_rate', sa.Float(), nullable=True),
    sa.Column('overall_assertiveness', sa.Integer(), nullable=True),
    sa.Column('sentence_completion_rate', sa.Integer(), nullable=True),
    sa.Column('upspeak_count_avg', sa.Float(), nullable=True),
    sa.Column('filler_by_topic', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hesitation_by_type', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assertiveness_weekly', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sessions_analysed', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.String(), server_default=sa.text('CAST(now() AS VARCHAR)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_patterns_user_id'), 'communication_patterns', ['user_id'], unique=True)
    op.create_table('conference_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meeting_type', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('avg_confidence', sa.Integer(), nullable=True),
    sa.Column('personas_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('coaching_tips_shown', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('CAST(now() AS VARCHAR)'), nullable=False),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conference_sessions_user_id'), 'conference_sessions', ['user_id'], unique=False)
    op.create_table('debate_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('total_rounds', sa.Integer(), nullable=False),
    sa.Column('avg_claim_score', sa.Float(), nullable=True),
    sa.Column('avg_evidence_score', sa.Float(), nullable=True),
    sa.Column('avg_rebuttal_score', sa.Float(), nullable=True),
    sa.Column('fallacies_detected', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('CAST(now() AS VARCHAR)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debate_sessions_user_id'), 'debate_sessions', ['user_id'], unique=False)
    op.create_table('exercise_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_type', sa.String(), nullable=False),
    sa.Column('warmup_step', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), server_default=sa.text('CAST(now() AS VARCHAR)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_logs_user_id'), 'exercise_logs', ['user_id'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('culture_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('domain_vocab', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('CAST(now() AS VARCHAR)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_user_id'), 'interview_sessions', ['user_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('fluency_score', sa.Integer(), nullable=True),
    sa.Column('vocab_score', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('new_words', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('CAST(now() AS VARCHAR)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_user_id'), 'journal_entries', ['user_id'], unique=False)
    op.create_table('practice_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=True),
    sa.Column('scenario_title', sa.String(), nullable=True),
    sa.Column('scenario_type', sa.String(), nullable=False),
    sa.Column('custom_prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('CAST(now() AS VARCHAR)'), nullable=False),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_sessions_user_id'), 'practice_sessions', ['user_id'], unique=False)
    op.create_table('progress_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('sessions_count', sa.Integer(), nullable=False),
    sa.Column('practice_minutes', sa.Integer(), nullable=False),
    sa.Column('avg_score', sa.Integer(), nullable=True),
    sa.Column('fluency', sa.Float(), nullable=True),
    sa.Column('grammar', sa.Float(), nullable=True),
    sa.Column('pronunciation', sa.Float(), nullable=True),
    sa.Column('vocabulary', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('activity_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_snapshots_user_id'), 'progress_snapshots', ['user_id'], unique=False)
    op.create_table('roadmap_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_items_user_id'), 'roadmap_items', ['user_id'], unique=False)
    op.create_table('vocabulary_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('phonetic', sa.String(), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('example_sentence', sa.Text(), nullable=True),
    sa.Column('articulation_tip', sa.Text(), nullable=True),
    sa.Column('phonemes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('saved_from', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('times_reviewed', sa.Integer(), nullable=False),
    sa.Column('is_mastered', sa.Boolean(), nullable=False),
    sa.Column('next_review_at', sa.String(), nullable=True),
    sa.Column('added_at', sa.String(), server_default=sa.text('CAST(now() AS VARCHAR)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_words_user_id'), 'vocabulary_words', ['user_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_words_word'), 'vocabulary_words', ['word'], unique=False)
    op.create_table('conference_transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('CAST(now() AS VARCHAR)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['conference_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conference_transcripts_session_id'), 'conference_transcripts', ['session_id'], unique=False)
    op.create_table('conversation_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_session_id', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('CAST(now() AS VARCHAR)'), nullable=False),
    sa.ForeignKeyConstraint(['practice_session_id'], ['practice_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_turns_practice_session_id'), 'conversation_turns', ['practice_session_id'], unique=False)
    op.create_table('debate_arguments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debate_session_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('claim_score', sa.Integer(), nullable=True),
    sa.Column('evidence_score', sa.Integer(), nullable=True),
    sa.Column('rebuttal_score', sa.Integer(), nullable=True),
    sa.Column('fallacy_detected', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('CAST(now() AS VARCHAR)'), nullable=False),
    sa.ForeignKeyConstraint(['debate_session_id'], ['debate_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debate_arguments_debate_session_id'), 'debate_arguments', ['debate_session_id'], unique=False)
    op.create_table('session_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_session_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('fluency_score', sa.Integer(), nullable=True),
    sa.Column('grammar_score', sa.Integer(), nullable=True),
    sa.Column('pronunciation_score', sa.Integer(), nullable=True),
    sa.Column('vocabulary_score', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('prev_fluency', sa.Integer(), nullable=True),
    sa.Column('prev_grammar', sa.Integer(), nullable=True),
    sa.Column('prev_pronunciation', sa.Integer(), nullable=True),
    sa.Column('prev_vocabulary', sa.Integer(), nullable=True),
    sa.Column('prev_confidence', sa.Integer(), nullable=True),
    sa.Column('filler_count', sa.Integer(), nullable=False),
    sa.Column('wpm', sa.Integer(), nullable=True),
    sa.Column('feedback_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vocabulary_saved', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['practice_session_id'], ['practice_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('practice_session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_reports')
    op.drop_index(op.f('ix_debate_arguments_debate_session_id'), table_name='debate_arguments')
    op.drop_table('debate_arguments')
    op.drop_index(op.f('ix_conversation_turns_practice_session_id'), table_name='conversation_turns')
    op.drop_table('conversation_turns')
    op.drop_index(op.f('ix_conference_transcripts_session_id'), table_name='conference_transcripts')
    op.drop_table('conference_transcripts')
    op.drop_index(op.f('ix_vocabulary_words_word'), table_name='vocabulary_words')
    op.drop_index(op.f('ix_vocabulary_words_user_id'), table_name='vocabulary_words')
    op.drop_table('vocabulary_words')
    op.drop_index(op.f('ix_roadmap_items_user_id'), table_name='roadmap_items')
    op.drop_table('roadmap_items')
    op.drop_index(op.f('ix_progress_snapshots_user_id'), table_name='progress_snapshots')
    op.drop_table('progress_snapshots')
    op.drop_index(op.f('ix_practice_sessions_user_id'), table_name='practice_sessions')
    op.drop_table('practice_sessions')
    op.drop_index(op.f('ix_journal_entries_user_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_interview_sessions_user_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_exercise_logs_user_id'), table_name='exercise_logs')
    op.drop_table('exercise_logs')
    op.drop_index(op.f('ix_debate_sessions_user_id'), table_name='debate_sessions')
    op.drop_table('debate_sessions')
    op.drop_index(op.f('ix_conference_sessions_user_id'), table_name='conference_sessions')
    op.drop_table('conference_sessions')
    op.drop_index(op.f('ix_communication_patterns_user_id'), table_name='communication_patterns')
    op.drop_table('communication_patterns')
    op.drop_index(op.f('ix_anxiety_assessments_user_id'), table_name='anxiety_assessments')
    op.drop_table('anxiety_assessments')
    op.drop_index(op.f('ix_achievements_user_id'), table_name='achievements')
    op.drop_table('achievements')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_anonymous_sessions_token'), table_name='anonymous_sessions')
    op.drop_table('anonymous_sessions')
    # ### end Alembic commands ###
